general {
    # Τι εντολή να τρέξει αν ζητηθεί κλείδωμα από το σύστημα (π.χ. loginctl lock-session)
    lock_cmd = qs ipc call nisfere-lock trigger
    
    # Τι να κάνει πριν μπει σε sleep/suspend (κλειδώνει την οθόνη)
    before_sleep_cmd = qs ipc call nisfere-lock trigger
    
    # Τι να κάνει όταν ξυπνήσει από sleep (ανοίγει ξανά τις οθόνες)
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1ο Στάδιο: Κλείδωμα Οθόνης (στα 5 λεπτά)
listener {
    timeout = 300
    on-timeout = qs ipc call nisfere-lock trigger
}

# 2ο Στάδιο: Σβήσιμο Οθόνης - DPMS (στα 10 λεπτά)
listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}